// Player pixel-art frames: 16x16 grids, one character per pixel, '.' = transparent.
//
// These are hand-authored (see the change-request appendix for the base
// "down/idle-0" frame) and the derived frames (bob, walk, back-of-head, side
// profile) were generated and visually verified with a throwaway script
// before being frozen here as plain data — see git history for that script
// if the derivation needs to be redone by hand.
//
// LEGEND maps each character to a *palette role* (see palette.js), not a
// literal color — textures.js swaps in a different player-color palette (or
// the ghost palette) per texture set from these same grids.
export const LEGEND = {
  '.': null, // transparent
  K: 'outline',
  H: 'accent', // hair/hat
  S: 'skin',
  E: 'outline', // eye — drawn in the outline color, not skin
  B: 'body',
  D: 'shade', // body shade
};

const DOWN_IDLE_0 = [
  '......KKKK......',
  '.....KHHHHK.....',
  '....KHHHHHHK....',
  '...KHHHHHHHHK...',
  '..KHHSSSSSSHHK..',
  '..KSSSSSSSSSSK..',
  '..KSSESSSSESSK..',
  '..KSSSSSSSSSSK..',
  '...KSSSSSSSSK...',
  '....KSSSSSSK....',
  '.....KHHHHK.....',
  '....KBBBBBBK....',
  '...KBBBBBBBBK...',
  '...KBDDDDDDBK...',
  '....KDD..DDK....',
  '....KKK..KKK....',
];
const DOWN_IDLE_1 = [
  '.....KHHHHK.....',
  '....KHHHHHHK....',
  '...KHHHHHHHHK...',
  '..KHHSSSSSSHHK..',
  '..KSSSSSSSSSSK..',
  '..KSSESSSSESSK..',
  '..KSSSSSSSSSSK..',
  '...KSSSSSSSSK...',
  '....KSSSSSSK....',
  '.....KHHHHK.....',
  '....KBBBBBBK....',
  '...KBBBBBBBBK...',
  '...KBDDDDDDBK...',
  '................',
  '....KDD..DDK....',
  '....KKK..KKK....',
];
const DOWN_WALK_0 = [
  '......KKKK......',
  '.....KHHHHK.....',
  '....KHHHHHHK....',
  '...KHHHHHHHHK...',
  '..KHHSSSSSSHHK..',
  '..KSSSSSSSSSSK..',
  '..KSSESSSSESSK..',
  '..KSSSSSSSSSSK..',
  '...KSSSSSSSSK...',
  '....KSSSSSSK....',
  '.....KHHHHK.....',
  '....KBBBBBBK....',
  '...KBBBBBBBBK...',
  '...KBDDDDDDBK...',
  '...KDD..DDK.....',
  '...KKK..KKK.....',
];
const DOWN_WALK_1 = [
  '......KKKK......',
  '.....KHHHHK.....',
  '....KHHHHHHK....',
  '...KHHHHHHHHK...',
  '..KHHSSSSSSHHK..',
  '..KSSSSSSSSSSK..',
  '..KSSESSSSESSK..',
  '..KSSSSSSSSSSK..',
  '...KSSSSSSSSK...',
  '....KSSSSSSK....',
  '.....KHHHHK.....',
  '....KBBBBBBK....',
  '...KBBBBBBBBK...',
  '...KBDDDDDDBK...',
  '.....KDD..DDK...',
  '.....KKK..KKK...',
];
const UP_IDLE_0 = [
  '......KKKK......',
  '.....KHHHHK.....',
  '....KHHHHHHK....',
  '...KHHHHHHHHK...',
  '..KHHHHHHHHHHK..',
  '..KHHHHHHHHHHK..',
  '..KHHHHHHHHHHK..',
  '..KHHHHHHHHHHK..',
  '...KHHHHHHHHK...',
  '....KHHHHHHK....',
  '.....KHHHHK.....',
  '....KBBBBBBK....',
  '...KBBBBBBBBK...',
  '...KBDDDDDDBK...',
  '....KDD..DDK....',
  '....KKK..KKK....',
];
const UP_IDLE_1 = [
  '.....KHHHHK.....',
  '....KHHHHHHK....',
  '...KHHHHHHHHK...',
  '..KHHSSSSSSHHK..',
  '..KHHHHHHHHHHK..',
  '..KHHHHHHHHHHK..',
  '..KHHHHHHHHHHK..',
  '...KHHHHHHHHK...',
  '....KHHHHHHK....',
  '.....KHHHHK.....',
  '....KBBBBBBK....',
  '...KBBBBBBBBK...',
  '...KBDDDDDDBK...',
  '................',
  '....KDD..DDK....',
  '....KKK..KKK....',
];
const UP_WALK_0 = [
  '......KKKK......',
  '.....KHHHHK.....',
  '....KHHHHHHK....',
  '...KHHHHHHHHK...',
  '..KHHHHHHHHHHK..',
  '..KHHHHHHHHHHK..',
  '..KHHHHHHHHHHK..',
  '..KHHHHHHHHHHK..',
  '...KHHHHHHHHK...',
  '....KHHHHHHK....',
  '.....KHHHHK.....',
  '....KBBBBBBK....',
  '...KBBBBBBBBK...',
  '...KBDDDDDDBK...',
  '...KDD..DDK.....',
  '...KKK..KKK.....',
];
const UP_WALK_1 = [
  '......KKKK......',
  '.....KHHHHK.....',
  '....KHHHHHHK....',
  '...KHHHHHHHHK...',
  '..KHHHHHHHHHHK..',
  '..KHHHHHHHHHHK..',
  '..KHHHHHHHHHHK..',
  '..KHHHHHHHHHHK..',
  '...KHHHHHHHHK...',
  '....KHHHHHHK....',
  '.....KHHHHK.....',
  '....KBBBBBBK....',
  '...KBBBBBBBBK...',
  '...KBDDDDDDBK...',
  '.....KDD..DDK...',
  '.....KKK..KKK...',
];
const SIDE_IDLE_0 = [
  '.......KKKK.....',
  '......KHHHHK....',
  '.....KHHHHHHK...',
  '....KHHHHHHHHK..',
  '...KHHSSSSSSHHK.',
  '...KSSSSSSSSSSK.',
  '...KSSSSSSSESSK.',
  '...KSSSSSSSSSSK.',
  '....KSSSSSSSSK..',
  '.....KSSSSSSK...',
  '......KHHHHK....',
  '.....KBBBBBBK...',
  '....KBBBBBBBBK..',
  '....KBDDDDDDBK..',
  '....KDD..DDK....',
  '....KKK..KKK....',
];
const SIDE_IDLE_1 = [
  '......KHHHHK....',
  '.....KHHHHHHK...',
  '....KHHHHHHHHK..',
  '...KHHSSSSSSHHK.',
  '...KSSSSSSSSSSK.',
  '...KSSSSSSSESSK.',
  '...KSSSSSSSSSSK.',
  '....KSSSSSSSSK..',
  '.....KSSSSSSK...',
  '......KHHHHK....',
  '.....KBBBBBBK...',
  '....KBBBBBBBBK..',
  '....KBDDDDDDBK..',
  '................',
  '....KDD..DDK....',
  '....KKK..KKK....',
];
const SIDE_WALK_0 = [
  '.......KKKK.....',
  '......KHHHHK....',
  '.....KHHHHHHK...',
  '....KHHHHHHHHK..',
  '...KHHSSSSSSHHK.',
  '...KSSSSSSSSSSK.',
  '...KSSSSSSSESSK.',
  '...KSSSSSSSSSSK.',
  '....KSSSSSSSSK..',
  '.....KSSSSSSK...',
  '......KHHHHK....',
  '.....KBBBBBBK...',
  '....KBBBBBBBBK..',
  '....KBDDDDDDBK..',
  '...KDD..DDK.....',
  '...KKK..KKK.....',
];
const SIDE_WALK_1 = [
  '.......KKKK.....',
  '......KHHHHK....',
  '.....KHHHHHHK...',
  '....KHHHHHHHHK..',
  '...KHHSSSSSSHHK.',
  '...KSSSSSSSSSSK.',
  '...KSSSSSSSESSK.',
  '...KSSSSSSSSSSK.',
  '....KSSSSSSSSK..',
  '.....KSSSSSSK...',
  '......KHHHHK....',
  '.....KBBBBBBK...',
  '....KBBBBBBBBK..',
  '....KBDDDDDDBK..',
  '.....KDD..DDK...',
  '.....KKK..KKK...',
];

// --- Dog (Summoner minion) ---
// Same 16x16 frame and LEGEND as the players, so it goes through the exact
// same palette-swap texture generator. ~12x11 px of dog, sitting low in the
// frame. Derived and visually verified the same way the player frames were.
const DOG_DOWN_IDLE_0 = [
  '................',
  '................',
  '................',
  '................',
  '...KK......KK...',
  '...KHK....KHK...',
  '...KHHKKKKHHK...',
  '...KHHHHHHHHK...',
  '...KHEHHHHEHK...',
  '...KHHHHHHHHK...',
  '....KHHKKHHK....',
  '.....KKKKKK.....',
  '..KBBBBBBBBBBK..',
  '..KBDDDDDDDDBK..',
  '..KK.KK..KK.KK..',
  '................',
];
const DOG_DOWN_IDLE_1 = [
  '................',
  '................',
  '................',
  '...KK......KK...',
  '...KHK....KHK...',
  '...KHHKKKKHHK...',
  '...KHHHHHHHHK...',
  '...KHEHHHHEHK...',
  '...KHHHHHHHHK...',
  '....KHHKKHHK....',
  '.....KKKKKK.....',
  '..KBBBBBBBBBBK..',
  '..KBDDDDDDDDBK..',
  '..KK.KK..KK.KK..',
  '................',
  '................',
];
const DOG_DOWN_WALK_0 = [
  '................',
  '................',
  '................',
  '................',
  '...KK......KK...',
  '...KHK....KHK...',
  '...KHHKKKKHHK...',
  '...KHHHHHHHHK...',
  '...KHEHHHHEHK...',
  '...KHHHHHHHHK...',
  '....KHHKKHHK....',
  '.....KKKKKK.....',
  '..KBBBBBBBBBBK..',
  '..KBDDDDDDDDBK..',
  '.KK.KK..KK.KK...',
  '................',
];
const DOG_DOWN_WALK_1 = [
  '................',
  '................',
  '................',
  '................',
  '...KK......KK...',
  '...KHK....KHK...',
  '...KHHKKKKHHK...',
  '...KHHHHHHHHK...',
  '...KHEHHHHEHK...',
  '...KHHHHHHHHK...',
  '....KHHKKHHK....',
  '.....KKKKKK.....',
  '..KBBBBBBBBBBK..',
  '..KBDDDDDDDDBK..',
  '...KK.KK..KK.KK.',
  '................',
];
const DOG_UP_IDLE_0 = [
  '................',
  '................',
  '................',
  '................',
  '...KK......KK...',
  '...KHK....KHK...',
  '...KHHKKKKHHK...',
  '...KHHHHHHHHK...',
  '...KHHHHHHHHK...',
  '...KHHHHHHHHK...',
  '....KHHKKHHK....',
  '.....KKKKKK.....',
  '..KBBBBBBBBBBK..',
  '..KBDDDDDDDDBK..',
  '..KK.KK..KK.KK..',
  '................',
];
const DOG_UP_IDLE_1 = [
  '................',
  '................',
  '................',
  '...KK......KK...',
  '...KHK....KHK...',
  '...KHHKKKKHHK...',
  '...KHHHHHHHHK...',
  '...KHHHHHHHHK...',
  '...KHHHHHHHHK...',
  '....KHHKKHHK....',
  '.....KKKKKK.....',
  '..KBBBBBBBBBBK..',
  '..KBDDDDDDDDBK..',
  '..KK.KK..KK.KK..',
  '................',
  '................',
];
const DOG_UP_WALK_0 = [
  '................',
  '................',
  '................',
  '................',
  '...KK......KK...',
  '...KHK....KHK...',
  '...KHHKKKKHHK...',
  '...KHHHHHHHHK...',
  '...KHHHHHHHHK...',
  '...KHHHHHHHHK...',
  '....KHHKKHHK....',
  '.....KKKKKK.....',
  '..KBBBBBBBBBBK..',
  '..KBDDDDDDDDBK..',
  '.KK.KK..KK.KK...',
  '................',
];
const DOG_UP_WALK_1 = [
  '................',
  '................',
  '................',
  '................',
  '...KK......KK...',
  '...KHK....KHK...',
  '...KHHKKKKHHK...',
  '...KHHHHHHHHK...',
  '...KHHHHHHHHK...',
  '...KHHHHHHHHK...',
  '....KHHKKHHK....',
  '.....KKKKKK.....',
  '..KBBBBBBBBBBK..',
  '..KBDDDDDDDDBK..',
  '...KK.KK..KK.KK.',
  '................',
];
const DOG_SIDE_IDLE_0 = [
  '................',
  '................',
  '................',
  '................',
  '....KK......KK..',
  '....KHK....KHK..',
  '....KHHKKKKHHK..',
  '....KHHHHHHHHK..',
  '....KHHHHHHEHK..',
  '....KHHHHHHHHK..',
  '.....KHHKKHHK...',
  '......KKKKKK....',
  '...KBBBBBBBBBBK.',
  '...KBDDDDDDDDBK.',
  '..KK.KK..KK.KK..',
  '................',
];
const DOG_SIDE_IDLE_1 = [
  '................',
  '................',
  '................',
  '....KK......KK..',
  '....KHK....KHK..',
  '....KHHKKKKHHK..',
  '....KHHHHHHHHK..',
  '....KHHHHHHEHK..',
  '....KHHHHHHHHK..',
  '.....KHHKKHHK...',
  '......KKKKKK....',
  '...KBBBBBBBBBBK.',
  '...KBDDDDDDDDBK.',
  '...KK.KK..KK.KK.',
  '................',
  '................',
];
const DOG_SIDE_WALK_0 = [
  '................',
  '................',
  '................',
  '................',
  '....KK......KK..',
  '....KHK....KHK..',
  '....KHHKKKKHHK..',
  '....KHHHHHHHHK..',
  '....KHHHHHHEHK..',
  '....KHHHHHHHHK..',
  '.....KHHKKHHK...',
  '......KKKKKK....',
  '...KBBBBBBBBBBK.',
  '...KBDDDDDDDDBK.',
  '.KK.KK..KK.KK...',
  '................',
];
const DOG_SIDE_WALK_1 = [
  '................',
  '................',
  '................',
  '................',
  '....KK......KK..',
  '....KHK....KHK..',
  '....KHHKKKKHHK..',
  '....KHHHHHHHHK..',
  '....KHHHHHHEHK..',
  '....KHHHHHHHHK..',
  '.....KHHKKHHK...',
  '......KKKKKK....',
  '...KBBBBBBBBBBK.',
  '...KBDDDDDDDDBK.',
  '...KK.KK..KK.KK.',
  '................',
];

// frame key -> grid, matching the texture frame contract `{idle|walk}-{down|up|side}-{0|1}`.
// "side" is authored facing right; the renderer flips it (setFlipX) for left.
export const PLAYER_FRAMES = {
  'idle-down-0': DOWN_IDLE_0,
  'idle-down-1': DOWN_IDLE_1,
  'walk-down-0': DOWN_WALK_0,
  'walk-down-1': DOWN_WALK_1,
  'idle-up-0': UP_IDLE_0,
  'idle-up-1': UP_IDLE_1,
  'walk-up-0': UP_WALK_0,
  'walk-up-1': UP_WALK_1,
  'idle-side-0': SIDE_IDLE_0,
  'idle-side-1': SIDE_IDLE_1,
  'walk-side-0': SIDE_WALK_0,
  'walk-side-1': SIDE_WALK_1,
};

export const PLAYER_FRAME_SIZE = 16;

/** Dog frames, same contract/frame names as PLAYER_FRAMES. */
export const DOG_FRAMES = {
  'idle-down-0': DOG_DOWN_IDLE_0,
  'idle-down-1': DOG_DOWN_IDLE_1,
  'walk-down-0': DOG_DOWN_WALK_0,
  'walk-down-1': DOG_DOWN_WALK_1,
  'idle-up-0': DOG_UP_IDLE_0,
  'idle-up-1': DOG_UP_IDLE_1,
  'walk-up-0': DOG_UP_WALK_0,
  'walk-up-1': DOG_UP_WALK_1,
  'idle-side-0': DOG_SIDE_IDLE_0,
  'idle-side-1': DOG_SIDE_IDLE_1,
  'walk-side-0': DOG_SIDE_WALK_0,
  'walk-side-1': DOG_SIDE_WALK_1,
};
